// このファイルはコメントと関数定義の問題を調査するためのものです

// 関数定義のテスト
def testFunc() : int -> int {
    🍕 + 1 >> 💩;
}

// コメントアウトされた行の後に関数定義
// これはコメントです
def afterComment() : int -> int {
    🍕 * 2 >> 💩;
}

5 |> testFunc |> print;
10 |> afterComment |> print;

// 複数行のコメントアウトのテスト
// 以下の行はコメントアウトされています
// def commentedFunc() : int -> int {
//     🍕 * 3 >> 💩;
// }

// コメントアウトの後に関数定義
def afterMultipleComments() : int -> int {
    🍕 / 2 >> 💩;
}

20 |> afterMultipleComments |> print;

// ケース1: コメントなしの関数定義と呼び出し
def case1Func() : int -> str {
    🍕 |> to_string >> 💩;
}

30 |> case1Func |> print;

// ケース2: 最初の呼び出しがコメントアウトされた関数定義と呼び出し
def case2Func() : int -> str {
    "Case 2: " + (🍕 |> to_string) >> 💩;
}

// 40 |> case2Func |> print;
50 |> case2Func |> print;